name: Nix Develop
description: Nix shell environments brought to GitHub Actions
author: nick novitski
inputs:
  arguments:
    description: Additional arguments to pass to the `nix develop` command
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ github.action_path }}/nix-develop-gha.sh ${{ inputs.arguments }}
